In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import joblib
import ast

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
Features = ['Speical_Char','Have_IP', 'Have_At','URL_length' ,'URL_Depth','Redirection', 'Time_get_redirect',
                        'port_in_url','use_http', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'https_Domain'
                        'Domain_lifespan', 'Domain_timeleft', 'same_asn','iFrame', 'Mouse_Over','Right_Click', 'Web_Forwards','eval','unescape',
                        'escape', 'ActiveXObject','fromCharCode','atob','Punny_Code']

In [15]:
df_origin = pd.read_csv("dataset/chongluadaov2.csv")
del df_origin['type']
df_train = pd.read_csv("cld.csv",names= ['url','features','labels'])

In [13]:
df_train['labels'].dtype

dtype('int64')

In [6]:
df_origin['labels'].dtype

dtype('int64')

In [7]:
inner = pd.merge(left=df_origin, right=df_train, left_on=['url','labels'], right_on=['url','labels'],how='left')
# del inner['urls']

In [8]:
inner.dropna(subset = ["features"], inplace=True)
inner

url  labels   type  \
5       http://jezebel.com/goodbye-revenge-ill-miss-ou...       0  train   
12                               http://wickedweaver.com/       1  train   
16            https://mail.google.com/a/recordedbooks.com       0    val   
33      http://richsportsmgmt.com/media/mod_languages/...       1   test   
35              http://www.i-m.mx/WEBMASTER8d/emailquota/       1  train   
...                                                   ...     ...    ...   
124328               https://plus.google.com/+Duoborgatto       0  train   
124330    https://www.ringcentral.com/products/sf2002.asp       0    val   
124331     https://plus.google.com/+BeautymissionPl/posts       0    val   
124332                             https://bit.ly/3vAfEWG       1  train   
124337  http://www.motomach3.cz/admin/Activation/cmd%3...       1    val   

                                                 features  
5       [2, 0, 0, 1, 1, 5, 1, 0, 1, 0, 0, 0, 0, 1, 0, ...  
12      [2, 0, 0, 0, 0, 5, 0, 0, 1, 0, 0, 0, 0, 1, 0, ...  
16      [4, 0, 0, 0, 2, 6, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
33      [3, 0, 0, 1, 4, 5, 0, 0, 1, 0, 1, 0, 0, 1, 0, ...  
35      [3, 0, 0, 0, 2, 5, 1, 0, 1, 0, 0, 1, 0, 1, 0, ...  
...                                                   ...  
124328  [4, 0, 0, 0, 1, 6, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
124330  [4, 0, 0, 0, 2, 6, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
124331  [4, 0, 0, 0, 2, 6, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
124332  [2, 0, 0, 0, 1, 6, 1, 1, 0, 0, 1, 0, 0, 1, 0, ...  
124337  [9, 0, 0, 1, 6, 5, 1, 0, 1, 0, 0, 0, 1, 1, 1, ...  

[18327 rows x 4 columns]

In [21]:
data_train = inner[inner['type'].str.contains("train")].dropna()
data_test  = inner[inner['type'].str.contains("test")].dropna()

In [22]:
data_train

url  labels   type  \
5       http://jezebel.com/goodbye-revenge-ill-miss-ou...       0  train   
12                               http://wickedweaver.com/       1  train   
35              http://www.i-m.mx/WEBMASTER8d/emailquota/       1  train   
37      http://www.regina.ninetendev.com/wp-admin/css/...       1  train   
51      https://www.pinterest.com/6xangel/slow-cooker-...       0  train   
...                                                   ...     ...    ...   
124292                        https://freeproductkey.org/       1  train   
124311  http://x-coder.blogspot.ru/2013/03/cara-membua...       1  train   
124326                               https://verisign.com       0  train   
124328               https://plus.google.com/+Duoborgatto       0  train   
124332                             https://bit.ly/3vAfEWG       1  train   

                                                 features  
5       [2, 0, 0, 1, 1, 5, 1, 0, 1, 0, 0, 0, 0, 1, 0, ...  
12      [2, 0, 0, 0, 0, 5, 0, 0, 1, 0, 0, 0, 0, 1, 0, ...  
35      [3, 0, 0, 0, 2, 5, 1, 0, 1, 0, 0, 1, 0, 1, 0, ...  
37      [5, 0, 0, 1, 4, 5, 1, 0, 1, 0, 0, 0, 0, 1, 0, ...  
51      [3, 0, 0, 1, 2, 6, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...  
...                                                   ...  
124292  [2, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
124311  [4, 0, 0, 1, 3, 5, 1, 1, 1, 0, 0, 1, 1, 1, 1, ...  
124326  [2, 0, 0, 0, 0, 6, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
124328  [4, 0, 0, 0, 1, 6, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
124332  [2, 0, 0, 0, 1, 6, 1, 1, 0, 0, 1, 0, 0, 1, 0, ...  

[13922 rows x 4 columns]

In [41]:
list(df_train['labels']).count(0)

59399

In [23]:
x = df_train['features'].values
type(x[0])

str

In [29]:
x = df_train['features'].values
y = df_train['labels'].values

# x = [np.array(i) for i in x]
x = [ast.literal_eval(i)[:-1] for i in x]
# x = [np.array(x).reshape(-1, 1) for x in x]

In [22]:
x[0]

array([[5],
       [0],
       [0],
       [0],
       [1],
       [6],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25, random_state =0 )

#----------------applying grid search to find best performing parameters 
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators': [100, 700],
    'max_features': ['sqrt', 'log2'],
    'criterion' :['gini', 'entropy']}]

grid_search = GridSearchCV(RandomForestClassifier(),  parameters,cv =5, n_jobs= -1)
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid=[{'criterion': ['gini', 'entropy'],
                          'max_features': ['sqrt', 'log2'],
                          'n_estimators': [100, 700]}])

In [31]:
print("Best Accurancy =" +str( grid_search.best_score_))
print("best parameters =" + str(grid_search.best_params_)) 

Best Accurancy =0.9735816867402779
best parameters ={'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}


In [32]:
#fitting RandomForest regression with best params 
classifier = RandomForestClassifier(n_estimators = 100, criterion = "entropy", max_features = 'sqrt',  random_state = 0)
classifier.fit(x_train, y_train)

#predicting the tests set result
y_pred = classifier.predict(x_test)

#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

#pickle file joblib
joblib.dump(classifier, 'rf_final.pkl')

[[14712   118]
 [  346  3133]]


['rf_final.pkl']

In [33]:
len(x[0]) == len(Features)

False

In [41]:
len(x[0])

28

In [42]:
len(Features)

26

In [14]:
names = np.array(Features)
importances =classifier.feature_importances_
sorted_importances = sorted(importances, reverse=True)
indices = np.argsort(-importances)

In [15]:
pd.DataFrame(sorted_importances, names[indices], columns=['importance'])

IndexError: index 26 is out of bounds for axis 0 with size 26

In [20]:
names = np.array(Features)
importances =classifier.feature_importances_
sorted_importances = sorted(importances, reverse=True)
indices = np.argsort(-importances)
var_imp = pd.DataFrame(sorted_importances, names[indices], columns=['importance'])

IndexError: index 26 is out of bounds for axis 0 with size 26

In [28]:
fi_df = var_imp

fi_df.sort_values(by=['importance'], ascending=False,inplace=True)

plt.figure(figsize=(10,8))
sns.barplot(x=fi_df['importance'], y=names)
#Add chart labels
plt.title('RANDOM FOREST FEATURE IMPORTANCE')
plt.xlabel('FEATURE IMPORTANCE')
plt.ylabel('FEATURE NAMES')

NameError: name 'var_imp' is not defined

# Testing

In [38]:
from feature_extraction import *

classifier = joblib.load('rf_final.pkl')

ext = Extractor()
url = "https://stackoverflow.com"
Vector = np.array(ext(url)[:-1])
print(Vector)
prediction = classifier.predict(Vector.reshape(1, -1))
print(prediction)

Domain Age:  6977
[2 0 0 0 0 6 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0]


In [57]:
Vector = np.array(ext("https://stackoverflow.com/questions/42179046/what-flavor-of-regex-does-visual-studio-code-use"))
print(Vector.reshape(-1, 1)[:-1])

Domain Age:  6977
[['2']
 ['0']
 ['0']
 ['1']
 ['3']
 ['6']
 ['0']
 ['0']
 ['0']
 ['0']
 ['0']
 ['0']
 ['0']
 ['1']
 ['0']
 ['0']
 ['0']
 ['0']
 ['0']
 ['1']
 ['0']
 ['0']
 ['0']
 ['0']
 ['0']
 ['0']
 ['0']
 ['0']]


In [62]:
Vector.shape
len(Vector[:-1])

27

In [ ]:
Vector

In [142]:
import json

with open('Generate Dataset/dataset/blacklist','r') as f:
    black = json.load(f)

In [144]:
black[0]

{'_id': '604bb52f6a1161c2e7d8608c',
 'url': 'http://2021-lmht.gq/*',
 'type': 'scam',
 'level': 'high',
 'meta': {}}

In [ ]:
for i in black:
    Vector = np.array(ext(i['url'])).reshape(1, -1)
    
    prediction = classifier.predict(Vector )
    print(prediction)

Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
Domain Age:  365
[0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
Domain Age:  365
[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
[0]
Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
[1]
Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
[1]
Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0]
[0]
Domain Age:  365
[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
[0]
Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0]
[0]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
Domain Age:  365
[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0

[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
[1]
[0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
[1]
Domain Age:  1826
[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[1]
Domain Age:  366
[0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
Domain Age:  365
[0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 3, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[0]
Domain Age:  5843
[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[1]
Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1,

[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
Domain Age:  365
[0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
Domain Age:  365
[0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[1]
Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0]
[0]
Domain Age:  731
[0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[1]
Domain Age:  731
[0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[1]
Domain Age:  365
[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[1]
Domain Age:  1096
[0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0]
[0]
Domain Age:  1096
[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]
[1]
Error trying to connect to socket: closing socket
[0, 0, 1, 0, 1, 0, 0, 0, 1, 1